# Generated by Django 4.2.13 on 2024-06-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
